### ISSUE TITLE
Autocomplete isn't bringing up results for postcodes when filtered by country

### ISSUE THREAD

**Issue by nicholasgriffintn** [klokantech/www.osmnames.org#15]

**Comment by MartinMikita** [comment]
Your issue should be posted in the search engine used on the web - https://github.com/klokantech/osmnames-sphinxsearch (see the [Software section](http://osmnames.org/download/#software) on Download page).

Please, submit this ticket there.

**Comment by nicholasgriffintn** [comment]
How many Github page do you guys have? Wow lol. No wonder you can't seem to work out where stuff goes..
