### ISSUE TITLE
Site is broken: CORS error

### ISSUE THREAD

**Issue by mnboos** [klokantech/www.osmnames.org#18]
The site doesn't appear to be working anymore, due to multiple CORS errors like

> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://maps.tilehosting.com/styles/bright/style.json?key=UFirA1lr6QcukgLJpmKq. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing)

**Comment by xkomczax** [comment]
fixed long time ago => closing
