### ISSUE TITLE
Make homepage more responsive

### ISSUE THREAD

**Issue by sfkeller** [klokantech/www.osmnames.org#4]
When loading homepage on a mobile phone (say for demo purposes - but not only) the geonames input line is almost unreachable and the JSON info output is displayed in an unreadable way.

**Comment by klokan** [comment]
Pull request is welcome ;-)

**Comment by sfkeller** [comment]
That was rather a note to self :-)

**Comment by sfkeller** [comment]
After the update the webpage is much more readable!
But now I'm missing any information when a place has been found. 
So one could add at least "type" and "country_code" which fits even to small screens.

**Comment by sfkeller** [comment]
... meanwhile: one could also add an OpenSearch entry for one-click search: https://en.wikipedia.org/wiki/OpenSearch
