### ISSUE TITLE
Update README.md for local compilation

### ISSUE THREAD

**Issue by klokan** [klokantech/www.osmnames.org#5]
We should update README.md and add a step-by-step guide how to compile this website on a local computer - it means cloning git including submodules, local installation of Jekyll and opening live preview on localhost http.

Reported problem while working on #4:

> On Tue, Feb 7, 2017 at 10:54 AM, Fritschi Severin <severin.fritschi@hsr.ch> wrote:
> I’m the intern at HSR who’s working on making OSMNames more responsive for mobile devices. However, despite my best efforts, I’m having difficulties building the site locally, so that it is displayed properly. So far I’ve tried setting up the github pages on my forked repository, where I was met with this error:
> 
> Your SCSS file base.scss has an error on line 11: Undefined variable: "$btn-fontweight"
> 
> I was unable to fix the issue, because I couldn’t find any reference to the variable above, apart from where it was initially declared in “_variables.scss”.
> I then went on to build the site using Jekyll and Docker, as you mentioned in the email to Stefan, but that led to no avail either. The site still wasn’t displayed properly.
> If you know what the underlying issue may be or have a different approach, I would be pleased to hear it.

Recommended:
https://help.github.com/articles/setting-up-your-github-pages-site-locally-with-jekyll/

**Comment by klokan** [comment]
BTW it sounds like you have not cloned the git repo correctly with the submodules - as the bug report suggests the version of "styles" submodule is different than the one really used in this repo.

**Comment by daliborjanak** [comment]
```
git clone <repo> --recursive
```
or later:
```
git submodule init
git submodule update
```

Install jekyll from:
https://jekyllrb.com/docs/installation/


go to directory and run
```
jekyll serve
```

If there will be still error that we have committed bad breakpoint on submodule.

**Comment by daliborjanak** [comment]
Added to readme in 2fc5a00e67b9b4364fcbf33111756376ca81bcb8. Tested locally. Works
